### PR TITLE
Implement UMI-tools: ReadDeduplicator

### PR DESCRIPTION
**Pull request by Goosang-Yu**
# UMI-tools in GenET

We can now perform UMI-tools([Smith et al. Genome Res. 2017](https://genome.cshlp.org/content/27/3/491.long)) functionality within GenET using a simple function. One of the powerful features of UMI-tools, deduplication, is available in the ```genet.analysis``` module. Additionally, we've made it compatible with our familiar format, ```pd.DataFrame```.

### CODE REVIEW

**Comment by ntfargo** [comment]
👍

**Comment by Goosang-Yu** [comment]
@ntfargo Thank you for check this PR.
I'll test this with few more data, and I'll merge next day if there are no bug found.

**Comment by Goosang-Yu** [comment]
I find something to fix, so I close this PR and make new PR.

**Comment by ntfargo** [comment]
Ok

**Pull request closed without merging**
